management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - env
          - metrics
          - prometheus
spring:
  application:
    name: verification-service
server:
  port: 9080
logging:
  level:
    org.springframework: DEBUG